#!/usr/bin/env bash
#>  40/.../[0-9][0-9].gz ----- merge ---> 40/.../leads.gz

(
set -u
set -o pipefail
set +x

find "../RESULT/40" -name "??.gz" | mergef -k=1,1n -k=2,2 -k=3,3n -k=4,4n -m --least=24 -incomplete="20: %t_%n.%e" -where 'only -nopr -all -older=3days' -tt="leads.gz"

)>>"$0.log" 2>&1
