#!/usr/bin/env bash
#>
(
set -u
set -x
set -o pipefail
cd `dirname $0`

lch_f=${1:? leads_channels file! }
[[ ! -s "$lch_f" ]] && echo "not found $lch_f">&2 && exit 1

# leads_channels file:
#labels="sid dom chan mark uid sec check sz expire chan_sec chan_bdom expired_chan expired_sec our_sec_hours_ago"
#         1   2    3    4   5   6    7    8    9      10        11           12          13            14           

our_metka=`conf conf.txt our_metka` # # значение нашей метки (="soloway")

# преобразуем leads_channels в такую структуру,
# после сумматоров получается типа такого (по каждому домену):
# домен * часов * лидов * лидов_накопительным_итогом
#220-volt.ru*0*21*21
#220-volt.ru*1*1*22
#220-volt.ru*2*1*23
#220-volt.ru*3*3*26
#220-volt.ru*17*1*27
#220-volt.ru*18*1*28
#220-volt.ru*20*1*29
#220-volt.ru*23*1*30
#220-volt.ru*28*1*31
#220-volt.ru*30*2*33
#220-volt.ru*47*1*34
#220-volt.ru*49*2*36
#220-volt.ru*81*2*38
#220-volt.ru*95*3*41

# там где лидов_накопительным_итогом станет > лидов соловья (берется из справочника %soloway_leads)
# из той строки возьмем кол-во часов - это и будет окно (в часах).

zcat $lch_f |
 awk -F* -v"OFS=*" '$3 && int($14/24)<$9 {print $2,$14}' | # ДОМЕН, ЧАСОВ_С_СОЛОВЬЯ, где лид приписан кому-то и с soloway был переход меньше, чем expire дней назад 
 sort -t\* -k1,1 -k2,2n | # отсортировано по домену, по возрастанию часов прошедших с перехода с соловья
 summator -fu=+cnt | # просуммировано количество случаев по ключу ДОМЕН+ЧАСОВ_С_СОЛОВЬЯ
 summator -la=2 -fu=vals,vals,+cumuls | # + колонка нарастающим итогом кол-во лидов
 lae -lb="dom hours linecnt cnt" '
 my %windows;
 my %soloway_leads = cat {-split=>"\\*"}, shift; # читается файл, переданный параметром и делаетя х-м { первое-поле => второе, ... }
 _{
  if ( my $solow_leads = $soloway_leads{ $F[DOM] }){
    if ( Cnt > $solow_leads ){
	if ( !$windows{ $F[DOM] }{ hours } or $windows{ $F[DOM] }{ hours } eq "NA"){
	    $windows{ $F[DOM] } = { hours=>Hours, cnt=>Cnt, soloway_leads=>$solow_leads };
	}    
    }else{
	$windows{ $F[DOM] }{ hours }="NA";
	$windows{ $F[DOM] }{ cnt } = Cnt;
	$windows{ $F[DOM] }{ soloway_leads } ||= $solow_leads;
    }
  }else{
    $windows{ $F[DOM] }{ hours }="NA";
    $windows{ $F[DOM] }{ cnt }="NA";
    $windows{ $F[DOM] }{ soloway_leads } = 0;
  }  
 };
 
 for my $dom (sort keys %windows){
    my $wind = $windows{$dom};
    p0 $dom, @{$wind}{qw| hours cnt soloway_leads |}
 }
 
' <( zcat "$lch_f" | awk -F* -v"our=$our_metka" '$3==our {print $2}' | summator -fu=+cnt ) # две колонки: домен,кол-во лидов соловья 








)#>>"$0.log" 2>&1

