#!/usr/bin/env bash

set +x
set -u
set -o pipefail
#set -e
#> 50_rep_04_light с выбранными полями (для Андрея и его виндовой утилиты)
#>? До конца не импортируется, все-таки. 
src_file=${1:?srcfile!}
res_file=${2:?resfile!}
day=`fn2days $src_file`
src_rep="../RESULT/50/$day/50_rep_04_light.gz"
[[ -s "$src_rep" ]] || exit 3
# 50_rep_04 format:
lb="date sid domain categ1 categ2 chan mvaldom uuids uids leads uleads chsum"
zcat "$src_rep" | cut -d* -f1,3,6,8,9,10,11,12

